modify cmd

diff --git a/cmd/read-config b/cmd/read-config
--- a/cmd/read-config
+++ b/cmd/read-config
@@ -32,36 +32,37 @@ fi
 CONFIG_KIND=""
 
 function mkFile() {
-    #echo "Donwload config file: ${fn} from ${url}"
+  #echo "Donwload config file: ${fn} from ${url}"
 
-      wget -O ${fn} ${url}
-      if [ $? -eq 1 ]; then
-        echo "Fail to downloade: ${url}"
-        return 1
-      fi
+  fp=${basedir}/deploy
+  wget -O ${fp}/${fn} ${url}
+  if [ $? -eq 1 ]; then
+    echo "Fail to downloade: ${url}"
+    return 1
+  fi
 
-      len=`${CTRLDIR}/cmd/jq '.propertySources | length' ${fn}`
-      for ((i=0;i<$len;i++));
-      do
-        nm=`${CTRLDIR}/cmd/jq ".propertySources[$i].name" ${fn}`
+  len=`${CTRLDIR}/cmd/jq '.propertySources | length' ${fp}/${fn}`
+  for ((i=0;i<$len;i++));
+  do
+    nm=`${CTRLDIR}/cmd/jq ".propertySources[$i].name" ${fp}/${fn}`
     if [ "${CONFIG_KIND}" == "secret" ] && [[ "$nm" =~ "application.properties" ]]; then
-        echo ""
+      echo ""
     elif [[ "$nm" =~ ".properties" ]]; then
-              #echo "$i => $nm"
+      #echo "$i => $nm"
 
-              chk=`${CTRLDIR}/cmd/jq ".propertySources[$i].source" ${fn} > $i-${fn}`
-              if [ $? -eq 0 ]; then
-                len2=`${CTRLDIR}/cmd/jq "keys | length" $i-${fn}`
+      chk=`${CTRLDIR}/cmd/jq ".propertySources[$i].source" ${fp}/${fn} > ${fp}/$i-${fn}`
+      if [ $? -eq 0 ]; then
+        len2=`${CTRLDIR}/cmd/jq "keys | length" ${fp}/$i-${fn}`
 
-                for ((j=0;j<$len2;j++))
-                do
-                      key=`${CTRLDIR}/cmd/jq -r "keys[$j]" $i-${fn}`
-                      val=`${CTRLDIR}/cmd/jq -r ".[\"$key\"]" $i-${fn}`
-                      echo "$key=$val" >> ${ofn}
-                done
-              fi
-        fi
-    done
+        for ((j=0;j<$len2;j++))
+          do
+            key=`${CTRLDIR}/cmd/jq -r "keys[$j]" ${fp}/$i-${fn}`
+            val=`${CTRLDIR}/cmd/jq -r ".[\"$key\"]" ${fp}/$i-${fn}`
+            echo "$key=$val" >> ${ofn}
+          done
+      fi
+    fi
+  done
 }
 
 # set download url 환경변수
@@ -69,11 +70,11 @@ INGRESS_CONFIG_SERVER=${configserver}
 
 
 # get config-server ingress host
-echo "STEP4. Get config server ingress host "
+echo "STEP2. Get config server ingress host "
 host=`kubectl get ing ${INGRESS_CONFIG_SERVER} -o yaml | grep host: | cut -d ":" -f 2 | tr -d " "`
 if [ "${host}" == "" ]; then
-    echo "CAN't get config server ingress address"
-    exit 1
+  echo "CAN't get config server ingress address"
+  exit 1
 fi
 
 url=""
@@ -81,9 +82,12 @@ fn=""
 uri="http://${host}/${appname}"
 
 # generage file depends on config kind
-echo "STEP5. Generate config file "
+echo "STEP3. Generate config file "
 
 configs=`echo ${config_kinds} | sed "s/,/ /g"`
+
+# create deploy directory 
+mkdir -p ${basedir}/deploy 
 
 for kind in ${configs}
 do
@@ -91,7 +95,7 @@ do
   echo "read config ->  ${kind}"
   fn=${kind}.json
   url=${uri}/${kind}-common,${kind}-${profile}
-  ofn=${basedir}/cicd/${kind}.properties
+  ofn=${basedir}/deploy/${kind}.properties
   echo "" > ${ofn}
 
   mkFile
@@ -101,4 +105,3 @@ echo ""
 echo "************** END READ CONFIG ***************"
 echo ""
 exit 0
-
